
package com.paquetexpress.webbooking.documentacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.paquetexpress.webbooking.documentacion.retorno.DataResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Documentacion", targetNamespace = "http://www.paquetexpress.com/webbooking/Documentacion/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.paquetexpress.webbooking.documentacion.ObjectFactory.class,
    com.paquetexpress.webbooking.documentacion.retorno.ObjectFactory.class
})
public interface Documentacion {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.paquetexpress.webbooking.documentacion.retorno.DataResponse
     */
    @WebMethod(action = "http://www.paquetexpress.com/webbooking/Documentacion/documentarGuia")
    @WebResult(name = "DataResponse", targetNamespace = "http://www.paquetexpress.com/webbooking/Documentacion/retorno", partName = "parameters")
    public DataResponse documentarGuia(
        @WebParam(name = "Data", targetNamespace = "http://www.paquetexpress.com/webbooking/Documentacion/", partName = "parameters")
        Data parameters);

}
