
package com.paquetexpress.webbooking.documentacion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import fedex.qa.ShipService;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Documentacion", targetNamespace = "http://www.paquetexpress.com/webbooking/Documentacion/", wsdlLocation = "src/META-INF/wsdl/DocumentacionSOAP.WSDL")
public class Documentacion_Service
    extends Service
{

    private final static URL DOCUMENTACION_WSDL_LOCATION;
    private final static WebServiceException DOCUMENTACION_EXCEPTION;
    private final static QName DOCUMENTACION_QNAME = new QName("http://www.paquetexpress.com/webbooking/Documentacion/", "Documentacion");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("wsdl/DocumentacionSOAP.WSDL");
            url = ShipService.class.getClassLoader().getResource("wsdl/DocumentacionSOAP.WSDL");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        DOCUMENTACION_WSDL_LOCATION = url;
        DOCUMENTACION_EXCEPTION = e;
    }

    public Documentacion_Service() {
        super(__getWsdlLocation(), DOCUMENTACION_QNAME);
    }

    public Documentacion_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOCUMENTACION_QNAME, features);
    }

    public Documentacion_Service(URL wsdlLocation) {
        super(wsdlLocation, DOCUMENTACION_QNAME);
    }

    public Documentacion_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOCUMENTACION_QNAME, features);
    }

    public Documentacion_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Documentacion_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Documentacion
     */
    @WebEndpoint(name = "DocumentacionSOAP")
    public Documentacion getDocumentacionSOAP() {
        return super.getPort(new QName("http://www.paquetexpress.com/webbooking/Documentacion/", "DocumentacionSOAP"), Documentacion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Documentacion
     */
    @WebEndpoint(name = "DocumentacionSOAP")
    public Documentacion getDocumentacionSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.paquetexpress.com/webbooking/Documentacion/", "DocumentacionSOAP"), Documentacion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOCUMENTACION_EXCEPTION!= null) {
            throw DOCUMENTACION_EXCEPTION;
        }
        return DOCUMENTACION_WSDL_LOCATION;
    }

}
