info:
  app:
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
    name: '@project.name@'
    version: '@project.version@'
server:
  port: 10443
spring:
  mvc:
    servlet:
      path: /@project.name@/v1
  main:
    banner-mode: off
