
package com.fedex.ws.track.v12;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShipService", targetNamespace = "http://fedex.com/ws/ship/v19", wsdlLocation = "src/META-INF/wsdl/ShipService_v19.wsdl")
public class ShipService
    extends Service
{

    private final static URL SHIPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SHIPSERVICE_EXCEPTION;
    private final static QName SHIPSERVICE_QNAME = new QName("http://fedex.com/ws/ship/v19", "ShipService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("classpath:/src/META-INF/wsdl/ShipService_v19.wsdl");
            url = ShipService.class.getClassLoader().getResource("wsdl/ShipService_v19.wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        SHIPSERVICE_WSDL_LOCATION = url;
        SHIPSERVICE_EXCEPTION = e;
    }

    public ShipService() {
        super(__getWsdlLocation(), SHIPSERVICE_QNAME);
    }

    public ShipService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHIPSERVICE_QNAME, features);
    }

    public ShipService(URL wsdlLocation) {
        super(wsdlLocation, SHIPSERVICE_QNAME);
    }

    public ShipService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHIPSERVICE_QNAME, features);
    }

    public ShipService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShipService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShipPortType
     */
    @WebEndpoint(name = "ShipServicePort")
    public ShipPortType getShipServicePort() {
        return super.getPort(new QName("http://fedex.com/ws/ship/v19", "ShipServicePort"), ShipPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShipPortType
     */
    @WebEndpoint(name = "ShipServicePort")
    public ShipPortType getShipServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fedex.com/ws/ship/v19", "ShipServicePort"), ShipPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHIPSERVICE_EXCEPTION!= null) {
            throw SHIPSERVICE_EXCEPTION;
        }
        return SHIPSERVICE_WSDL_LOCATION;
    }

}
