
package com.fedex.ws.track.v12;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TrackService", targetNamespace = "http://fedex.com/ws/track/v12", wsdlLocation = "src/META-INF/wsdl/TrackService_v12.wsdl")
public class TrackService
    extends Service
{

    private final static URL TRACKSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRACKSERVICE_EXCEPTION;
    private final static QName TRACKSERVICE_QNAME = new QName("http://fedex.com/ws/track/v12", "TrackService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("file:/E:/Users/dparra/Documents/Desarrollo/ECOM/FEDEX/FedExWebServiceStandardWSDL/TrackService/TrackService_v12.wsdl");
            url = ShipService.class.getClassLoader().getResource("wsdl/TrackService_v12.wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        TRACKSERVICE_WSDL_LOCATION = url;
        TRACKSERVICE_EXCEPTION = e;
    }

    public TrackService() {
        super(__getWsdlLocation(), TRACKSERVICE_QNAME);
    }

    public TrackService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRACKSERVICE_QNAME, features);
    }

    public TrackService(URL wsdlLocation) {
        super(wsdlLocation, TRACKSERVICE_QNAME);
    }

    public TrackService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRACKSERVICE_QNAME, features);
    }

    public TrackService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrackService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TrackPortType
     */
    @WebEndpoint(name = "TrackServicePort")
    public TrackPortType getTrackServicePort() {
        return super.getPort(new QName("http://fedex.com/ws/track/v12", "TrackServicePort"), TrackPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrackPortType
     */
    @WebEndpoint(name = "TrackServicePort")
    public TrackPortType getTrackServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fedex.com/ws/track/v12", "TrackServicePort"), TrackPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRACKSERVICE_EXCEPTION!= null) {
            throw TRACKSERVICE_EXCEPTION;
        }
        return TRACKSERVICE_WSDL_LOCATION;
    }

}
